### ISSUE TITLE
Pip problems causing hashbangctl to crash

### ISSUE THREAD

**Issue by erinzm** [hashbang/hashbangctl#12] opened 2016-03-04 21:09 UTC
When `sudo hashbangctl` is run, Pip/setuptools gets mad and spits out

```
Traceback (most recent call last):
  File "/usr/local/bin/hashbangctl", line 4, in <module>
    __import__('pkg_resources').require('hashbangctl==0.2')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: hashbangctl==0.2
```

@KellerFuchs started to diagnose:

```
2016-03-04 21:00:39     KellerFuchs     Oh fsck, I think I know
2016-03-04 21:00:50     KellerFuchs     pip is a pip of shit that installs in /tmp
2016-03-04 21:00:55     KellerFuchs     and /tmp got compartmented
```

**Comment by erinzm** [comment] 2016-03-11 16:38
Pingety-ping @KellerFuchs?

**Comment by KellerFuchs** [comment] 2016-03-12 05:03
@ArchimedesPi I've been pretty dead & unavailable lately.
Basically, the issue is `pip` having installed things in `/tmp`.  Since I'm not exactly knowledgeable about `pip`, perhaps another @hashbang/administrators can pipe in and bring a solution while I'm not available?

**Comment by KellerFuchs** [comment] 2016-03-17 20:23
Fixed by https://github.com/hashbang/admin-tools/commit/fc3a586c5909b7eeb34e30dcd95110c21de1dec5

Thanks a bunch to @pjdelport for the help on `#pypa`.

**Closed as completed by KellerFuchs** 2016-03-17 20:23 UTC
